[package]
name    = "queue"
version = "0.1.0"
edition = "2021"
description = "runtime/queue — TaskQueue-Trait + MemoryQueue"

[dependencies]
async-trait = { workspace = true }
tokio       = { workspace = true }
uuid        = { workspace = true }
anyhow      = { workspace = true }
tracing     = { workspace = true }
serde_json  = { workspace = true }
redis       = { workspace = true }
types       = { workspace = true }
errors      = { workspace = true }
